#!/bin/bash
# setup-cpuminer-blackshirt.sh
# One-file installer for cpuminer-blackshirt ARM64
# Downloads binary, asks config questions, generates start script
# Blackshirt Crypto — blkshirtpool.com

INSTALL_DIR=~/cpuminer-blackshirt
REPO="https://github.com/blackshirt-crypto/cpuminer-android-blackshirt/releases/download/v26.2"
BINARY="cpuminer-arm64-v26.2"

clear
echo ""
echo "  ╔══════════════════════════════════════╗"
echo "  ║   cpuminer-blackshirt  ARM64 Setup   ║"
echo "  ║   Blackshirt Crypto                  ║"
echo "  ╚══════════════════════════════════════╝"
echo ""

# Create install directory
mkdir -p "$INSTALL_DIR"
echo "[1/3] Created install directory: $INSTALL_DIR"
echo ""

# Download binary
echo "[2/3] Downloading cpuminer-blackshirt binary..."
curl -L --progress-bar -o "$INSTALL_DIR/cpuminer-blackshirt" "$REPO/$BINARY"
if [ $? -ne 0 ] || [ ! -s "$INSTALL_DIR/cpuminer-blackshirt" ]; then
    echo "ERROR: Download failed. Check your internet connection and try again."
    exit 1
fi
chmod +x "$INSTALL_DIR/cpuminer-blackshirt"
echo "Binary downloaded successfully."
echo ""

# Download reconfigure.sh
echo "[3/3] Downloading reconfigure.sh..."
curl -L --progress-bar -o "$INSTALL_DIR/reconfigure.sh" "$REPO/reconfigure.sh"
chmod +x "$INSTALL_DIR/reconfigure.sh"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Mining Configuration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Choose your mining algorithm below."
echo "  Enter the TYPE shown — not the coin ticker."
echo "  Example: type 'civiclight' for CivicNet, not 'CIVIC'"
echo ""
echo "  TYPE           COIN"
echo "  ─────────────────────────────────────"
echo "  civiclight     CivicNet (CIVIC)"
echo "  yespowerr16    Yenten (YTN)"
echo "  yescryptr16    Fennec (FNNC)"
echo "  yespower       various yespower coins"
echo "  sha256d        various SHA-256d coins"
echo "  scrypt         various scrypt coins"
echo "  whirlpool      CapStash (CAP)"
echo ""
read -p "  Algorithm type: " ALGO

if [ -z "$ALGO" ]; then
    echo "ERROR: Algorithm is required."
    exit 1
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Pool Configuration"
echo "  Format: stratum+tcp://HOSTNAME:PORT"
echo "  Example: stratum+tcp://blkshirtpool.com:4353"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
read -p "  Primary pool: " POOL

if [ -z "$POOL" ]; then
    echo "ERROR: Primary pool is required."
    exit 1
fi

read -p "  Backup pool (optional, press Enter to skip): " POOL2

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Wallet & Worker"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
read -p "  Wallet address: " WALLET

if [ -z "$WALLET" ]; then
    echo "ERROR: Wallet address is required."
    exit 1
fi

read -p "  Worker name (optional, press Enter to skip): " WORKER
if [ -n "$WORKER" ]; then
    WORKER_STRING=".$WORKER"
else
    WORKER_STRING=""
fi

read -p "  Password (default: x, press Enter to use x): " PASS
PASS=${PASS:-x}

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Thread Selection"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
MAX_THREADS=$(nproc)
echo "  Your device has $MAX_THREADS CPU cores available."
echo "  Tip: on big.LITTLE phones, fewer threads often = more hash"
echo "  Recommended: test 4, 6, and 8 to find your sweet spot"
echo ""
while true; do
    read -p "  Threads (1-$MAX_THREADS): " THREADS
    if [[ "$THREADS" =~ ^[0-9]+$ ]] && [ "$THREADS" -ge 1 ] && [ "$THREADS" -le "$MAX_THREADS" ]; then
        break
    fi
    echo "  Please enter a number between 1 and $MAX_THREADS."
done

# Generate start script
SAVEFILE="$INSTALL_DIR/start-${ALGO}.sh"

cat > "$SAVEFILE" << EOF
#!/bin/bash
# cpuminer-blackshirt — $ALGO
# Generated by setup-cpuminer-blackshirt.sh
# Run ~/cpuminer-blackshirt/reconfigure.sh to change settings
ALGO=$ALGO
POOL=$POOL
POOL2=$POOL2
WALLET=${WALLET}${WORKER_STRING}
PASS=$PASS
THREADS=$THREADS
EOF

cat >> "$SAVEFILE" << 'LAUNCHEOF'

INSTALL_DIR=~/cpuminer-blackshirt
MINER="$INSTALL_DIR/cpuminer-blackshirt"
LOG="/tmp/cpuminer-${ALGO}.log"
> "$LOG"

# Build pool args
POOL_ARGS="-o $POOL"
if [ -n "$POOL2" ]; then
    POOL_ARGS="$POOL_ARGS -o $POOL2"
fi

# Launch miner
"$MINER" -a "$ALGO" $POOL_ARGS -u "$WALLET" -p "$PASS" -t "$THREADS" 2>&1 | tee -a "$LOG" &
MINER_PID=$!

trap "kill $MINER_PID 2>/dev/null; echo ''; echo 'Miner stopped.'; exit 0" INT TERM

sleep 3

# Dashboard
while kill -0 $MINER_PID 2>/dev/null; do
    clear
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  cpuminer-blackshirt  |  algo: $ALGO"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  Pool:    $POOL"
    if [ -n "$POOL2" ]; then
    echo "  Backup:  $POOL2"
    fi
    echo "  Wallet:  ${WALLET:0:24}..."
    echo "  Threads: $THREADS"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

    HASHRATE=$(grep -oE '\([0-9]+\.[0-9]+h/s\)' "$LOG" | tail -1 | tr -d '()hs/')
    ACCEPTED=$(grep 'Accepted' "$LOG" | tail -1 | awk '{print $3}')
    REJECTED=$(grep 'Rejected' "$LOG" | tail -1 | awk '{print $3}')
    RATIO=$(grep 'Accepted' "$LOG" | tail -1 | grep -oE '[0-9]+\.[0-9]+%')
    TEMP=$(grep -oE 'curr [0-9]+ C' "$LOG" | tail -1 | grep -oE '[0-9]+')
    BLOCK=$(grep -oE 'New Block [0-9]+' "$LOG" | tail -1 | grep -oE '[0-9]+')
    SHARERATE=$(grep 'Share rate' "$LOG" | tail -1 | awk '{print $3}')
    TTF=$(grep -oE 'Share [0-9]+[ms][0-9]*[ms]*' "$LOG" | tail -1 | sed 's/Share //')

    if grep -q 'Stratum connection established' "$LOG" && ! grep -q 'connection failed\|connection reset' <(tail -5 "$LOG"); then
        STATUS="Connected"
    else
        STATUS="Connecting..."
    fi

    echo "  Status:   $STATUS"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    printf "  Hashrate: %-15s CPU Temp: %s C\n" "${HASHRATE:--.--} H/s" "${TEMP:---}"
    printf "  Accepted: %-15s Rejected: %s\n" "${ACCEPTED:-0}" "${REJECTED:-0}"
    printf "  Accept %%: %-15s Share/min: %s\n" "${RATIO:----}" "${SHARERATE:----}"
    printf "  Next share: %-13s Block:    %s\n" "${TTF:----}" "${BLOCK:----}"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  Press Ctrl+C to stop"
    echo ""

    sleep 15
done

echo "Miner process ended."
LAUNCHEOF

chmod +x "$SAVEFILE"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Setup Complete!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Files installed to: $INSTALL_DIR"
echo "    cpuminer-blackshirt  — miner binary"
echo "    start-${ALGO}.sh     — your start script"
echo "    reconfigure.sh       — change settings later"
echo ""
echo "  To mine now:"
echo "    $SAVEFILE"
echo ""
echo "  To mine later:"
echo "    ~/cpuminer-blackshirt/start-${ALGO}.sh"
echo ""
echo "  To change settings:"
echo "    ~/cpuminer-blackshirt/reconfigure.sh"
echo ""
echo "  Starting miner now..."
echo ""
exec "$SAVEFILE"
